[versions]
lwjgl = "3.4.2"
joml = "1.10.9"
imgui = "1.92.7.1"
junit = "6.0.0"

[libraries]
lwjgl-bom = { module = "org.lwjgl:lwjgl-bom", version.ref = "lwjgl" }

lwjgl = { module = "org.lwjgl:lwjgl" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl" }

joml = { module = "org.joml:joml", version.ref = "joml" }

imgui-binding = { module = "io.github.spair:imgui-java-binding", version.ref = "imgui" }
imgui-lwjgl3 = { module = "io.github.spair:imgui-java-lwjgl3", version.ref = "imgui" }
imgui-natives-linux = { module = "io.github.spair:imgui-java-natives-linux", version.ref = "imgui" }
imgui-natives-windows = { module = "io.github.spair:imgui-java-natives-windows", version.ref = "imgui" }
imgui-natives-macos = { module = "io.github.spair:imgui-java-natives-macos", version.ref = "imgui" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }